spring:
  datasource:
    url: jdbc:mysql://192.168.0.41:3306/sunflowerdb
    username: gangnam
    password: gangnam
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 755327441125-4d1ao9ejaedh3lqhkus8dd9arr9fdu5u.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
            redirect-uri: "http://localhost:1601/login/oauth2/code/google"
        provider:
          google:
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
server:
  port: 1601
