spring:
  datasource:
    url: jdbc:mysql://localhost:3306/login
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none

server:
  port: 3013

file:
  upload:
    path: C:/uploads
    server-url: ""
