spring:
  datasource:
    url: jdbc:mysql://192.168.0.53:3306/sunflowerdb
    username: gangnam
    password: gangnam
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 3013